<?php $this->layout('system::layout/default') ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-8">
        <div class="card shadow border-0 border-radius-12">
            <div class="card-body">

                <?php if (! empty($data['errors'])): ?>
                    <div>
                        <?= $this->fetch(
                            'system::app/alert',
                            [
                                'alert_type' => 'alert-danger',
                                'alert'      => $data['errors'],
                            ]
                        ) ?>
                    </div>
                <?php endif ?>

                <h4 class="card-title"><?= $page_title ?></h4>
                <form action="<?= $data['action_url'] ?>" method="post">
                    <div class="form-group">
                        <label for="name"><?= __('Article name') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="255"
                               name="name"
                               id="name"
                               required
                               value="<?= $data['fields']['name'] ?>"
                               placeholder="<?= __('Article name') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="page_title"><?= __('Page title') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="255"
                               name="page_title"
                               id="page_title"
                               required
                               value="<?= $data['fields']['page_title'] ?>"
                               placeholder="<?= __('Page title') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="code"><?= __('Article code') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="255"
                               name="code"
                               id="code"
                               value="<?= $data['fields']['code'] ?>"
                               placeholder="<?= __('Article code') ?>"
                        >
                        <div class="small text-muted"><?= __('Leave it empty for automatic generation') ?></div>
                    </div>
                    <div class="form-group">
                        <label for="keywords"><?= __('Keywords') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="255"
                               name="keywords"
                               id="keywords"
                               value="<?= $data['fields']['keywords'] ?>"
                               placeholder="<?= __('Keywords') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="description"><?= __('Description') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="255"
                               name="description"
                               id="description"
                               value="<?= $data['fields']['description'] ?>"
                               placeholder="<?= __('Description') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="preview_text"><?= __('Preview text') ?></label>
                        <textarea id="preview_text" class="form-control" name="preview_text"><?= $this->e($data['fields']['preview_text']) ?></textarea>
                    </div>
                    <div class="form-group">
                        <label for="text"><?= __('Text') ?></label>
                        <textarea id="text" class="form-control" name="text"><?= $this->e($data['fields']['text']) ?></textarea>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
                        <a href="<?= $data['back_url'] ?>" class="btn btn-outline-primary ml-2"><?= __('Back') ?></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
