<?php

/**
 * @var $data
 * @var \Blog\Models\BlogArticle $article
 * @var \Blog\Models\BlogSection $current_section
 */

$this->layout('system::layout/default');

?>
<div id="blog">
    <div class="p-no-margin">
        <?= $article->text_safe ?>
    </div>

    <div class="article-stat border-top border-bottom d-flex align-items-center pt-2 pb-2 mt-3">
        <div class="d-flex align-items-center mr-4">
            <div class="d-flex align-items-center mr-2"><?= __('Rating:') ?></div>
            <article-likes
                :article_id="<?= $article->id ?>"
                :plus="5"
                :minus="4"
                :rating="213"
                :can_vote="<?= $user->isValid() ? 'true' : 'false' ?>"
                :voted="1"
            ></article-likes>
        </div>
        <?php if ($article->view_count): ?>
            <div class="d-flex justify-content-end">
                <div class="text-muted forum-view-counter">
                    <svg class="icon download-button-icon mt-n1">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#eye"></use>
                    </svg>
                    <?= $article->view_count ?>
                </div>
            </div>
        <?php endif ?>
    </div>

    <div class="mt-3">
        <a href="<?= $current_section->url ?>"><?= __('Back') ?></a>
    </div>
</div>

<?php $this->push('styles') ?>
<link rel="stylesheet" href="<?= $this->asset('blog/css/blog.css', true) ?>">
<?php $this->stop(); ?>
<?php $this->push('scripts') ?>
<script src="<?= $this->asset('blog/js/blog.js', true) ?>"></script>
<script async charset="utf-8" src="//cdn.embedly.com/widgets/platform.js"></script>
<script>
    document.querySelectorAll('oembed[url]').forEach(element => {
        const anchor = document.createElement('a');
        anchor.setAttribute('href', element.getAttribute('url'));
        anchor.className = 'embedly-card';
        element.appendChild(anchor);
    });
</script>
<?php $this->stop(); ?>
