<?php

/**
 * @var $title
 * @var $page_title
 * @var $data
 * @var $current_section
 */

$this->layout('system::layout/default');
?>

<div class="row">
    <div class="col-12 col-xl-9">
        <?php if ($articles->count() > 0): ?>
            <?php foreach ($articles as $article): ?>
                <div class="card border-0 mb-2 shadow">
                    <div class="card-body">
                        <h3 class="card-title"><a href="<?= $article->code ?>"><?= $article->name ?></a></h3>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class="mt-3">
                <?= $articles->render() ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-12 col-xl-3">
        <?php if ($sections->count() > 0): ?>
            <h3 class="pl-3"><?= __('Categories') ?></h3>
            <nav class="nav flex-column">
                <?php foreach ($sections as $section): ?>
                    <a class="nav-link" href="<?= $section->url ?>"><?= $section->name ?></a>
                <?php endforeach; ?>
            </nav>
        <?php endif; ?>
    </div>
</div>
