<?php
/**
 * @var Johncms\System\Users\User $user
 * @var $blog_sections
 */

$ads = di(Johncms\Ads::class);
$ads_array = $ads->getAds();
?>
<?php if (! empty($ads_array['before_menu'])): ?>
    <div class="pl-4 pr-3 pt-3">
        <?php foreach ($ads_array['before_menu'] as $item): ?>
            <div><?= $item ?></div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<div class="accordion flex-grow-1" id="accordionAdmin">
    <ul class="nav nav__vertical">
        <?php foreach ($blog_sections as $key => $section): ?>
            <?php /** @var $section \Blog\Models\BlogSection */ ?>
            <li>
                <a href="<?= $section->url ?>">
                    <svg class="icon flex-shrink-0">
                        <use xlink:href="<?= $this->asset('blog/icons/icons.svg') ?>#folder"/>
                    </svg>
                    <span class="flex-grow-1"><?= $section->name ?></span>
                </a>
            </li>
        <?php endforeach; ?>
        <?php if ($user->rights >= 9): ?>
            <li class="border-top mt-3 border-bottom">
                <a href="/blog/admin/" class="py-3">
                    <svg class="icon text-danger">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#settings"/>
                    </svg>
                    <span class="flex-grow-1 text-danger"><?= d__('system', 'Admin Panel') ?></span>
                </a>
            </li>
        <?php endif ?>
    </ul>
</div>

<!-- Footer -->
<div class="sidebar__footer">
    <?php if (! empty($ads_array['after_menu'])): ?>
        <div class="pr-3 pt-2 mb-2">
            <?php foreach ($ads_array['after_menu'] as $item): ?>
                <div><?= $item ?></div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <div>
        <a href="/online/">
            <svg class="icon sidebar_online">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
            </svg>
            <?= $container->get('counters')->online() ?>
        </a>
    </div>
    <?php if (count($config['lng_list']) > 1): ?>
        <div class="mt-1">
            <button class="btn btn-link pl-0" data-url="/language/" data-toggle="modal" data-target=".ajax_modal">
                <img src="<?= $this->asset('images/flags/' . strtolower($locale) . '.png') ?>" alt="<?= $locale ?>">
                <?= $config['lng_list'][$locale] ?>
            </button>
        </div>
    <?php endif ?>
</div>
